- name: Direct License Bypass & Build APK
        run: |
          # 1. Check karein ki spec file hai ya nahi, aur license add karein
          echo "android.accept_sdk_license = True" >> buildozer.spec
          
          # 2. Seedha APK build karein (init nahi chalana hai)
          buildozer android debug
